### ISSUE TITLE
Fix Country Code in International Currency

### ISSUE THREAD

**Issue by KoolPal** [razorpay/razorpay-woocommerce#101]
Using the latest beta version.

While trying a test transaction using AUD $, I can see the modal showing the country code partially as A$

This looks weird

![image](https://user-images.githubusercontent.com/454883/56013562-ec7c3880-5d0e-11e9-8399-39972b5d5851.png)

![image](https://user-images.githubusercontent.com/454883/56013623-4f6dcf80-5d0f-11e9-80b1-958da0514590.png)

Please show the complete COUNTRY Code as **AUD** $ XYZ with appropriate spacing.

Thanks

**Comment by captn3m0** [comment]
Thanks for the report, I've filed an issue for this internally.

**Comment by umanghome** [comment]
`A$` is a valid symbol for AUD, and it is [not recommended](https://www.translationdirectory.com/article167.htm) to leave a space between the figure and the symbol. `A$55` is valid, but I agree that `A$55` looks a bit weird since `$` and `55` have similar shapes.

**Comment by KoolPal** [comment]
> `A$` is a valid symbol for AUD, and it is [not recommended](https://www.translationdirectory.com/article167.htm) to leave a space between the figure and the symbol. `A$55` is valid, but I agree that `A$55` looks a bit weird since `$` and `55` have similar shapes.

@umanghome I am not sure if you have read the item in the link **you shared** yourself.

Abbreviations
When an amount is mentioned, place the accepted abbreviation before the figure, **leaving a space between the abbreviation for a currency** and the amount, unless the abbreviation includes a currency symbol

**Comment by umanghome** [comment]
`AED` is an abbreivation. `A$` is a symbol. `AED 55` would be correct, and so would `A$55`.

**Comment by KoolPal** [comment]
> but I agree that `A$55` looks a bit weird since `$` and `55` have similar shapes.

What about introducing some spacing between the whole thing?
