### ISSUE TITLE
Version number problem

### ISSUE THREAD

**Issue by spinozarabel** [razorpay/razorpay-woocommerce#105]
You have a version number problem.
I have your plugin installed using git clone of your repo and on branch master and yet WP insists on telling me to upgrade to version from 1.63 to 1.65.

**Comment by captn3m0** [comment]
Yes, this is a known issue. (The version was bumped in readme.txt, but not `razorpay-payments.php`)

Will get resolved in the 2.0 stable release

**Comment by captn3m0** [comment]
Resolved in the 2.0.1 release
