### ISSUE TITLE
Do WooCommerce 3.6 compatibility test

### ISSUE THREAD

**Issue by imanuelrajan** [razorpay/razorpay-woocommerce#106]
Kindly make the plugin compatible to WooCommerce 3.6, released today.

**Comment by captn3m0** [comment]
It works: https://github.com/razorpay/razorpay-woocommerce/commit/26432d08135a4df5818088e019176a676215ae6f

Will show up as Supported in the next release.

**Comment by imanuelrajan** [comment]
when 2.0 will officially release???

**Comment by captn3m0** [comment]
We're waiting for beta-testers to report any issues prior to a stable release.

**Comment by KoolPal** [comment]
> We're waiting for beta-testers to report any issues prior to a stable release.
 But you are not responding to the issues raised by beta-testers!

**Comment by captn3m0** [comment]
2.0.1 has been released with updates on Supported versions:

- Wordpress 5.2-RC1
- WooCommerce 3.6.2
