### ISSUE TITLE
Fetching payment of bank transfer has problem

### ISSUE THREAD

**Issue by spinozarabel** [razorpay/razorpay-woocommerce#108]
Hi, I am using this plugin to fetch payments made to virtual accounts to reconcile against Woocommerce orders.
Your bank transfer function as it exists is not working: This is as shown below:

public function bankTransfer()
    {
        $relativeUrl = $this->getEntityUrl() . $this->id . '/bank_transfer';
        return $this->request('GET', $relativeUrl);
    }

I get an error saying that URL is not valid. I find that the id is not being passed. I modified it be as below and passed the id as parameter as shown:
public function bankTransfer($id)
    {
        $relativeUrl = $this->getEntityUrl() . $id . '/bank_transfer';

        return $this->request('GET', $relativeUrl);
    }

This works just fine. Do you have any comments? Is there something really wrong with your code ? If so can you check and fix it?

I am calling this as follows from the webhook:
protected function getVaPaymentEntity($razorpayPaymentId, $data)
    {
        try
        {
            $payment = $this->api->payment->bankTransfer($razorpayPaymentId);
        }
        catch (Exception $e)
        {
            $log = array(
                'message'         => $e->getMessage(),
                'payment_id'      => $razorpayPaymentId,
                'event'           => $data['event']
            );

            error_log(json_encode($log));

            exit;
        }

        return $payment;
    }

**Comment by captn3m0** [comment]
The documentation for razorpay-php states the exact usage:

`$bankTransfer    = $api->payment->fetch('pay_8JpVEWsoNPKdQh')->bankTransfer();`

Please check the correct usage: https://github.com/razorpay/razorpay-php
