### ISSUE TITLE
Plugin activation issue

### ISSUE THREAD

**Issue by imanuelrajan** [razorpay/razorpay-woocommerce#110]
Issue while uploading and activating Razorpay for WooCommerce 2.0

https://drive.google.com/file/d/1k_a1J70znLYgwHy0Ik_ZWCnpq3BKx687/view?usp=drivesdk

**Comment by imanuelrajan** [comment]
This issue is happening while I download source code zip and upload in WordPress

**Comment by imanuelrajan** [comment]
When I try to install Razorpay from WordPress plugin directory and activate, both WordPress 2.0.0 and 1.6.5 is getting install. The message shows the plugin deactivated for fatal issues.

**Comment by imanuelrajan** [comment]
https://drive.google.com/file/d/1kZTHdoks4veafOJ7wvZYbz_Uw0-IqksA/view?usp=drivesdk

https://drive.google.com/file/d/1jFYhEAuBlub0FiMtXW92W0BVtue9UYfg/view?usp=drivesdk

**Comment by captn3m0** [comment]
This is resolved now. Please upgrade to 2.0.1

**Comment by imanuelrajan** [comment]
Send me the 2.0.1 downloadable link

**Comment by imanuelrajan** [comment]
Issue solved
