### ISSUE TITLE
Payment Success message not shown on Order Pay page

### ISSUE THREAD

**Issue by KoolPal** [razorpay/razorpay-woocommerce#111]
Hi,

WooCommerce version: 3.6.2
WordPress version: 5.1.1
Razorpay for WooCommerce: Version 2.0.1

After successful payment, the customer sees the below screen
![image](https://user-images.githubusercontent.com/454883/57076579-9b58d680-6d07-11e9-8fe5-ad46e055a1c5.png)

Now if the customer moves to ANY Other link, he is shown the payment success message.
![image](https://user-images.githubusercontent.com/454883/57076603-a875c580-6d07-11e9-81de-aaa5b096ec85.png)

This looks weird.

Is there some setting to be changed in the plugin OR  is this a bug?

**Comment by captn3m0** [comment]
Looks like a bug, the message is supposed to be shown on the first screen. 

Wondering if the flash message can just be removed, since WooCommerce already shows a success message.

**Comment by KoolPal** [comment]
@captn3m0 In my view you can remove the flash message. It is redundant since There is a default Thank you page which most store owners would / could customize.

**Comment by KoolPal** [comment]
@captn3m0 Please ignore this. I think this seems to be a StoreFront Theme specific issue. :man_facepalming:
