### ISSUE TITLE
Fix Country Code for International Currency

### ISSUE THREAD

**Issue by KoolPal** [razorpay/razorpay-woocommerce#112]
Hi,

I  am forced to create another issue for this topic since you have incorrectly closed an existing issue #101

Earlier version of your plugin showed:
![image](https://user-images.githubusercontent.com/454883/57369992-acdd2b00-71ac-11e9-8187-a15d5ae86c33.png)
![image](https://user-images.githubusercontent.com/454883/57370005-b1a1df00-71ac-11e9-9679-d8a6f4b1fd9a.png)

I had requested you to show the complete COUNTRY Code as AUD $ XYZ with appropriate spacing.

Your latest version takes a step backwards by showing NO country indicator
![image](https://user-images.githubusercontent.com/454883/57370906-eca51200-71ae-11e9-857a-99e453ddbd63.png)
![image](https://user-images.githubusercontent.com/454883/57370913-f2025c80-71ae-11e9-98df-e941ad500b96.png)

Now the customer will be clueless about which currency he is being charged in!

I hope you do realize that there are many countries using the $ as a currency symbol. US, Singapore, Australia to name a few.

Please see how others are implementing this:

Aliexpress:
![image](https://user-images.githubusercontent.com/454883/57369913-70113400-71ac-11e9-834b-9f01ab757115.png)

![image](https://user-images.githubusercontent.com/454883/57369929-7d2e2300-71ac-11e9-9b76-be40bc7d7733.png)
 
Overstock.com
![image](https://user-images.githubusercontent.com/454883/57371405-4a862980-71b0-11e9-9b59-f28d02b7b6d6.png)

**Comment by KoolPal** [comment]
@umanghome Any update on this? It has been 7 days now.

**Comment by umanghome** [comment]
This is WIP. We'll be updating symbol and adding a space before the figure.

**Comment by KoolPal** [comment]
@umanghome Any update on this?

**Comment by umanghome** [comment]
We've added a space between the symbol and the figure.

**Comment by KoolPal** [comment]
@umanghome It would have been great if you had read & understood the entire issue thread before replying!

The ASK is for the country ISO code in ADDITION to the Symbol and amount. Specially with reference to the $ which is used across different countries.

Is this concept too difficult for you to understand? Do you think you need to ask around with some seniors?

I hope you guys can provide a decent resolution in next few days instead of just dragging this around!

**Comment by captn3m0** [comment]
Please keep discussions civil here.

**Comment by KoolPal** [comment]
@captn3m0 Please focus on providing solutions to your customers to ensure you have jobs and get your salary.

Closing a github issue as a reaction to honest feedback just shows your attitude towards your customers!

Do you realize that we are wanting to use your application so that YOUR company EARNS money from our business? Or are you thinking that we are asking you for all this for fun? This application is not some freeware game!

Get real guys!

**Comment by umanghome** [comment]
Your previously filed issue [mentioned](https://github.com/razorpay/razorpay-woocommerce/issues/101#issuecomment-488219121) having spacing as one of the requirements, which we decided to go with.

**Comment by KoolPal** [comment]
@umanghome That comment was when you were showing country code in the modal.
 
![image](https://user-images.githubusercontent.com/454883/58700810-c2fe9580-83be-11e9-8713-976633f6854b.png)
![image](https://user-images.githubusercontent.com/454883/58700814-c6921c80-83be-11e9-9f3b-973dd4bdd562.png)

Now you have removed the country code which does not make sense.
![image](https://user-images.githubusercontent.com/454883/58700848-e45f8180-83be-11e9-9b6e-5dd75a713a70.png)
![image](https://user-images.githubusercontent.com/454883/58700852-ea556280-83be-11e9-8d8b-5622098f0b31.png)

Please read this issue from the beginning for clear understanding.

Thanks

**Comment by isaumya** [comment]
Yes I agree. This is truly an annoying issue. Get this fixed. Razorpay team really have a very bad technical support at GitHub. After multiple emails they updated the gravity forms plugin after 2 years with some basic updates. Still no support to subscription.
