### ISSUE TITLE
Redirecting to /wc-api/razorpay after checkout

### ISSUE THREAD

**Issue by pSnehanshu** [razorpay/razorpay-woocommerce#114]
After completing checkout, the plugin is redirecting to `/wc-api/razorpay` whereas it should redirect to `/?wc-api=razorpay`. Please help me on how to fix this.
Razorpay v2.0.1
Woocommerce v3.6.4
WordPress v5.2.2

**Comment by pSnehanshu** [comment]
I guess the problem is due to this commit. https://github.com/razorpay/razorpay-woocommerce/pull/60/commits/8ba0cc09ac23fb0f261ece7a335f7b8e6d7c6da1#diff-1249d2a410f944514df25976d7e02709L279

**Comment by ramth05** [comment]
Can you please check Permalink Settings of your site from admin. This issue is related with url  settings.

**Comment by pSnehanshu** [comment]
What should i check? It is left as is, not changed.

**Comment by ramth05** [comment]
Can you please try "Common settings" as "Day and name" in place of "Plain" url's.  if not fixed, Please share the screens of your "Permalink Settings".

**Comment by pSnehanshu** [comment]
![permalinks](https://user-images.githubusercontent.com/9392350/60333000-9d60ae00-99b5-11e9-90e2-c9614155859f.png)
I said it is in default.

**Comment by ravijordan** [comment]
this is my permalink, but still it's nor working
i am getting response as 1
![image](https://user-images.githubusercontent.com/11586523/66681178-c4ef3400-ec8f-11e9-8db0-74e942d4da99.png)
Permalink 
![image](https://user-images.githubusercontent.com/11586523/66682535-06351300-ec93-11e9-9a6b-9cda5b7ca952.png)

**Comment by ramth05** [comment]
Hi Ravi,

Can you please try with 'Day and time' in place of 'Post name'.

**Comment by prem-techchefs** [comment]
@ravijordan  We hope this solution work for you. If still this issue occurs please let us know.
