### ISSUE TITLE
When a payment is created the woocommerce order gets completed

### ISSUE THREAD

**Issue by itw-dev** [razorpay/razorpay-woocommerce#116]
When a client starts a payment and drops from the payment page, the order gets completed instead of failing, how can this be corrected

**Comment by irfnhm** [comment]
You can notify the WooCommerce system using "webhooks". You can do something like this:
`case 'payment.failed':
					$log_content .= ' ' . sprintf(  'Payment %s failed.', $payment_id );
					break;`

**Comment by prem-techchefs** [comment]
@itw-dev  Please with our latest [Razorpay Woocommerce](https://wordpress.org/plugins/woo-razorpay/) plugin and enable webhook from woocommerce payment setting and same in razorpay webhook setting. Please let us in case if its not work.
