### ISSUE TITLE
I am getting Error while initiating the checkout. {"code":"BAD_REQUEST_ERROR","description":"The id provided does not exist"}

### ISSUE THREAD

**Issue by deathstroke007** [razorpay/razorpay-woocommerce#120]

**Comment by harman28** [comment]
@deathstroke007 Could you try using the latest plugin version, i.e. [v2.1.0](https://github.com/razorpay/razorpay-woocommerce/releases)? We fixed an issue that might be the same one you're facing.

**Comment by deathstroke007** [comment]
It started working in v1.5.8. Actually, I was passing "order_id" as shown in the Razorpay docs. I was just checking the flow and didn't call the orders API. Now, I am not passing and it is working. Thanks for the response though.

**Comment by harman28** [comment]
@deathstroke007 `order_id` does need to be passed if you're using [Orders API](https://razorpay.com/docs/payment-gateway/orders/). There are several advantages around doing so, but it requires you to make an API call before the payment request, and then use the resultant order id in the payment creation step.

**Comment by deathstroke007** [comment]
Yes. I was just testing for the first time. Now I get it. There is one more question, I am implementing in Android and whenever the failure happens like Bank down or some issue at the bank side, it asks the user for the Payment Retry but will razorpay call my webhook for the failed transaction. And plus onpaymenterror doesn't gets called in Android side.
