### ISSUE TITLE
Call to undefined method WC_Razorpay::handleCurrencyConversion()

### ISSUE THREAD

**Issue by devendrabhandari** [razorpay/razorpay-woocommerce#121]
I am getting below error at the time of checkout

Fatal error: Uncaught Error: Call to undefined method WC_Razorpay::handleCurrencyConversion()

**Comment by ramth05** [comment]
@devendrabhandari , which version you are using for razorpay-woocommerce.

**Comment by ramth05** [comment]
@devendrabhandari , looks like you are using old version of plugin. Can you please try the latest one.

**Comment by harman28** [comment]
Fixed in latest version.

**Comment by devendrabhandari** [comment]
@ramth05 we were using the latest version of the plugin. @harman28 thanks for the information. Now I will remove the patch.
