### ISSUE TITLE
Woocommerce subscription fails but payment on Razorpay shows successful

### ISSUE THREAD

**Issue by amodoke** [razorpay/razorpay-woocommerce#125]
After coming back from payment page, woocommerce shows payment failed due to "invalid signature", but the Razorpay dashboard shows the payment has been captured.

So exactly what needs to be done here?

Happens on both, test and live modes.

**Comment by prem-techchefs** [comment]
@amodoke  So you have to enable webhook in woocommerce razorpay payment and set **Webhook Secret**  and update same **Webhook Secret**  on razorpay dashboard setting. If still this will not work please post here.
