### ISSUE TITLE
Webhook failed

### ISSUE THREAD

**Issue by thesfboy** [razorpay/razorpay-woocommerce#126]
Keep getting continuous email alerts saying the webhook has failed. Today, I got 200+ emails. This has been going on for the past 6 months now. What the hell is happening? I have complained many times to your support team via chat and email and every time I get a reply saying you guys are working on it. IF you are not serious about Woocommerce then you shouldn't do this. As a result, I have deactivated the plugin and it is your loss. The other plugins like PayPal and PayTM work superbly. It is a simple issue and yet you have been unable to resolve it. Highly disappointed.

**Comment by harman28** [comment]
Sorry for the delay in seeing this. Ending up responding [on a different thread](https://github.com/razorpay/razorpay-woocommerce/issues/131#issuecomment-549707423). Closing this for now, but please feel free to reopen if the issue persists.
