### ISSUE TITLE
save card

### ISSUE THREAD

**Issue by kamal87g** [razorpay/razorpay-woocommerce#127]
Hi Team

Can you provide support to save the card for payment, I saw in your API it have the functionality to process the saved card.
can you please add the above functionality in plugin as well.
if this is not free support, Let me know how much you will charge for this.

**Comment by captn3m0** [comment]
The woocommerce plugin already supports saving cards for the customers using https://razorpay.com/flashcheckout/

If the customer provides the same phone number again for the payment (which is picked up from the user's address) - we will use the same card.
