### ISSUE TITLE
Redirects to WC-api after successfully payment

### ISSUE THREAD

**Issue by ravijordan** [razorpay/razorpay-woocommerce#128]
Even after reading many blogs and everything and also trying out the correct code given on github by your team, i am still getting the issue please help me in fixing this.
![image](https://user-images.githubusercontent.com/11586523/66681178-c4ef3400-ec8f-11e9-8db0-74e942d4da99.png)

**Comment by prem-techchefs** [comment]
@ravijordan  Please check your environment some outgoing requests are restricted or download our latest plugin from [here](https://wordpress.org/plugins/woo-razorpay/).
