### ISSUE TITLE
WC_Shortcode_Checkout->output deprecated call 

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-woocommerce#14]
Notice: WC_Shortcode_Checkout->output was called with an argument that is deprecated since version 2.1! "order" is no longer used to pass an order ID. Use the order-pay or order-received endpoint instead. in /www/wp-includes/functions.php on line 3891

Appears on the "Pay for Order" page.

**Comment by mayankamencherla** [comment]
Upgrade to latest version of woocommerce - 1.2.11 will fix the issue. Closing ticket.

**Comment by lordton** [comment]
same problem. i am updated to the latest version.

**Comment by ashussen** [comment]
I still got exactly the same error message.
I use woocommerce.2.6.11.

**Comment by captn3m0** [comment]
@ashussen Please give the versions for the following:

- PHP
- Wordpress
- WooCommerce Razorpay Plugin

to help us debug this.

**Comment by rsaravanan** [comment]
@captn3m0 

PHP : version 5.6.23
Wordpress: version 4.4.7
WooCommerce Razorpay Plugin: version 1.3.1
WooCommerce : version 2.6.14

Still I got the same error.

**Comment by captn3m0** [comment]
What we noticed in other cases was that some other extension was interfering and overriding the checks. Can you disable other extensions and see if the error persists? We are following the woocommerce guidelines on how this is supposed to be implemented.

**Comment by rsaravanan** [comment]
Other extensions mean installed in WP  or Woocommerce ext. ?

**Comment by rsaravanan** [comment]
Yes. I have disabled other extensions like Woocomerce Brands Pro, Theme Check which I have used in my website. Now Woocommerce and WooCommerce Razorpay Payments are only plugin is activated on my website.

Still showing the same error.

**Comment by captn3m0** [comment]
@rsaravanan Can you provide a link to your website?

**Comment by rsaravanan** [comment]
http://stage.zohomart.com/

**Comment by rsaravanan** [comment]
@captn3m0 any update ?

**Comment by captn3m0** [comment]
Thanks a lot, I've been able to replicate the issue. You'll get an update once we push out a fix.

Meanwhile, since this is just a notice, you can prevent it by setting `WP_DEBUG` to `false` in your `wp-config.php`. This should be the case for your production site.

**Comment by rsaravanan** [comment]
Thanks @captn3m0

**Comment by captn3m0** [comment]
@rsaravanan I've pushed out a new release (1.3.2) for this: https://wordpress.org/plugins/woo-razorpay/

**Comment by rsaravanan** [comment]
Thanks @captn3m0
