### ISSUE TITLE
make razorpay for woocommerce plugin compatible with woocommerce 3.9.0 and wordpress 5.3.2

### ISSUE THREAD

**Issue by imanuelrajan** [razorpay/razorpay-woocommerce#144]
make **razorpay for woocommerce** plugin compatible with woocommerce 3.9.0 and wordpress 5.3.2

**Comment by prem-techchefs** [comment]
@imanuelrajan  Can you please install available version of [razorpay-woocommerce](https://wordpress.org/plugins/woo-razorpay/).  As of now current release is also compatible for woocommerce 3.9.0 and wordpress 5.3.2 . If you face any error let us now please.
