### ISSUE TITLE
 'cURL error 6: Could not resolve host: api.razorpay.com'.

### ISSUE THREAD

**Issue by MAULIK882** [razorpay/razorpay-woocommerce#146]
Today I got an update for version 2.4.1 but after update getting error following error
 'cURL error 6: Could not resolve host: api.razorpay.com'.
so I thought its problem with api but after update api its still not working so reactive plugin but still worth less. then i decided to go back to version 2.4.0 but now this version also not working

**Comment by harman28** [comment]
Looks like outgoing requests are restricted on your environment. Are you able to send request to any other URL, aside from that of Razorpay? Do you need to do some domain whitelisting?

**Comment by MAULIK882** [comment]
> Looks like outgoing requests are restricted on your environment. Are you able to send request to any other URL, aside from that of Razorpay? Do you need to do some domain whitelisting?

Yes, it's working fine with stripe payment gateway. no, I don't think I need domain whitelisting because before update to version 2.4.1 it's working fine without any problem  but now version 2.4.0 also not working I disable some plugin which I enable for security purpose but still getting an error

**Comment by harman28** [comment]
Possible that this is happening due to a TLS version issue? You won't be able to make requests if you're still using TLS 1.0. More details here: https://razorpay.com/docs/announcements/tls/

**Comment by mplusdaya** [comment]
facing same issue on digital ocean server
