### ISSUE TITLE
Redirecting to /wc-api/razorpay after checkout

### ISSUE THREAD

**Issue by SkillToHire** [razorpay/razorpay-woocommerce#149]
After completing checkout, the plugin is redirecting to /wc-api/razorpay .
 Please help me on how to fix this.
Razorpay v2.4.1
Woocommerce v4.1.0
WordPress v 5.4

**Comment by ukveda** [comment]
@SkillToHire  Go to Setting - Permalink - Change permalink from "plain" to "day and name" then save changes.

**Comment by ChetanGN** [comment]
Fixed in issue [#152](https://github.com/razorpay/razorpay-woocommerce/pull/152)
