### ISSUE TITLE
Redirecting to /wc-api/razorpay after checkout please check it

### ISSUE THREAD

**Issue by SkillToHire** [razorpay/razorpay-woocommerce#150]
After completing checkout, the plugin is redirecting to /wc-api/razorpay .
 Please help me on how to fix this.
Razorpay v2.4.1
Woocommerce v4.1.0
WordPress v 5.4

**Comment by ramth05** [comment]
@SkillToHire , Can you please check your `Permalink Settings`, this issue related with that only

**Comment by prem-techchefs** [comment]
@SkillToHire  Please change your `Permalink Settings` from **plain**  to **Day and name**. This will work. Please let us know if you still facing issue.
