### ISSUE TITLE
After payment successful it shows page with. 1 written

### ISSUE THREAD

**Issue by thediveshsharma** [razorpay/razorpay-woocommerce#164]
![IMG_20200822_210652](https://user-images.githubusercontent.com/64721283/90960023-550b2600-e4bc-11ea-8fc1-3c31d89f2e1e.jpg)
Getting this page after payment successful.. please help me.. urgently

**Comment by thediveshsharma** [comment]
As per my knowledge I didn't modify the plugin code whatsoever. I just
installed the plugin as it is and the issue started arising..
I am using a paid theme by whiskers , maybe its happening because of their
codes in the theme. They have stopped providing support for the theme now.
So I can't even contact them .
Here are all the details you need .
1) https://whiskers.cmsmasters.net/pet-store/ (Theme I am using)
2) Wordpress 5.5
3) Razorpay for woocommerce version 2.5.0
4) Woocommerce version 4.4.1
…

**Comment by ChetanGN** [comment]
Fixed in issue [#152](https://github.com/razorpay/razorpay-woocommerce/pull/152)

**Comment by japhetobsioma** [comment]
I have the same issue, but I can see here (https://github.com/razorpay/razorpay-woocommerce/pull/152#issuecomment-678948001) that @thediveshsharma give the staging logins and @ChetanGN fix it for him which is I dont want to do. Maybe give some info on how you fix it? @ChetanGN Thanks.
