### ISSUE TITLE
Logo during checkout has a lot of width (whitespace)

### ISSUE THREAD

**Issue by Ayyub-Kolsawala** [razorpay/razorpay-woocommerce#169]
Hey there, I am adding razorpay payment gateway on a client's website running on Woocommerce for checkout. I noticed that when the user gets the checkout page the logo has a lot of width (whitespace) towards the right. 

Logo's Screenshot - https://cdn.razorpay.com/static/assets/logo/payment.svg

![image](https://user-images.githubusercontent.com/20044256/101273842-137a5e80-37bf-11eb-84f1-abae887cb8a3.png)

During checkout with `float:right`

![image](https://user-images.githubusercontent.com/20044256/101273899-a9ae8480-37bf-11eb-9692-59ad36f7182b.png)

Is it possible to remove the additional space from the above logo? I understand that I can replace the logo from the PHP file but I think it's better to have it fixed in the code itself.

**Comment by moon0326** [comment]
Bump

Pining @ChetanGN as you're most active in this repository 👍 

This is causing layout issues on various themes.

![#28663](https://user-images.githubusercontent.com/4723145/103242373-c9daea80-490a-11eb-978d-38a28aad05c6.jpg)

**Comment by ChetanGN** [comment]
@Ayyub-Kolsawala @moon0326 Thanks for writing to us. We will fix this in the upcoming release.

**Comment by Ayyub-Kolsawala** [comment]
> @Ayyub-Kolsawala @moon0326 Thanks for writing to us. We will fix this in the upcoming release.

Thanks @ChetanGN
