### ISSUE TITLE
Redirect url after payment success

### ISSUE THREAD

**Issue by saideep10** [razorpay/razorpay-woocommerce#17]
Hi,

I have installed woocommerce and razorpay-woocommerce plugin to my wordpress site and i  added 1 product to store in woocommerce.I did a payment after checkout.After the payment was success it redirected to this endpoint  /?wc-api=WC_Razorpay which it says is not working.Is there an order success page by default which is not showing in mycase .If its not present ,i want to redirect it to specfic page .Can you please help me on this

**Comment by captn3m0** [comment]
We redirect now to the my-order page which is what WC recommends.

**Comment by ravijordan** [comment]
this code still gets error.
![image](https://user-images.githubusercontent.com/11586523/66681178-c4ef3400-ec8f-11e9-8db0-74e942d4da99.png)
 please check with this error. after successfull payment it redirect to this page.

**Comment by ravijordan** [comment]
this is my permalink,  
![image](https://user-images.githubusercontent.com/11586523/66682481-db4abf00-ec92-11e9-951f-cbd9d64122f6.png)

**Comment by ravijordan** [comment]
this is my permalink, but still it's nor working
i am getting response as 1
![image](https://user-images.githubusercontent.com/11586523/66681178-c4ef3400-ec8f-11e9-8db0-74e942d4da99.png)
Permalink 
![image](https://user-images.githubusercontent.com/11586523/66682535-06351300-ec93-11e9-9a6b-9cda5b7ca952.png)
