### ISSUE TITLE
Woocommerce mails are not working with the orders that have Razorpay invloved

### ISSUE THREAD

**Issue by baau** [razorpay/razorpay-woocommerce#5]
Hello, 

I have a wordpress website and have been using the Razorpay plugin for collecting online payments. But the woocommerce is not sending any emails to the new customers when the customers pay through Razorpay, however the email are perfectly sent when the user opts for Direct Bank transfer option. 
Please help as soon as possible.

**Comment by captn3m0** [comment]
We have done extensive testing as a result of this report, and we have found no issues with how Razorpay interacts with woocommerce with respect to emails.

Please see the WooCommerce FAQ: https://docs.woocommerce.com/document/email-faq/

As it specifies, the order is converted to `processing` by Razorpay once the customer finishes the payment. From there, it is your woocommerce configuration that must send the mail.

Go to the `WooCommerce > Settings > Email` section and make sure that you are sending out mails for "Processing" status.
