### ISSUE TITLE
Razor pay plugin not getting activated

### ISSUE THREAD

**Issue by padwalkar** [razorpay/razorpay-woocommerce#518]
Hi Team,

I was trying to activate this woo-commerce plugin but I am getting this fatal error and the plugin fails to activate

> Plugin could not be activated because it triggered a fatal error.
> Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /way/to/wordpress-directory/wp-content/plugins/woo-razorpay/includes/razorpay-webhook.php on line 15

I have been waiting for almost a year and now when my account gets activated the plugin doesn't work there is also no technical team support, don't know how to contact Razorpay support... I hope at least the technical team reads these issues.

**Comment by yashgit891** [comment]
@padwalkar are you trying with the latest version of the plugin? If yes please check with php 7.1 or above and check if the issue persists.

**Comment by padwalkar** [comment]
Hi Team,

Below are the specification of my configuration
php version: 7.0.33-0
Apache: 2.4.18

Can I use some other version of plugin for this configuration?

**Comment by yashgit891** [comment]
Hello @padwalkar , you can try version v3.9.2, but we would recommend updating the php version to 7.1+.

**Comment by padwalkar** [comment]
Thanks... v3.9.2, this version worked
