### ISSUE TITLE
Issue with Wordpress 4.8 and WooCommerce 3.1.1

### ISSUE THREAD

**Issue by saurabhjn** [razorpay/razorpay-woocommerce#53]
In file razorpay-payments.php, there is a reference to wc_add_notice. This needs to change to a reference to $woocommerce->wc_add_notice. Otherwise an error is thrown.

**Comment by captn3m0** [comment]
We'll get this fixed in the next release.

**Comment by mayankamencherla** [comment]
Hi @saurabhjn , we are unable to replicate the issue locally with the same version numbers. 
Could you please share your PHP version number as well as a log / screenshot of the error?

**Comment by captn3m0** [comment]
Closing this issue, as we've tested this and `wc_add_notice` is [supported in WC3.1](https://docs.woocommerce.com/wc-apidocs/source-function-wc_add_notice.html#67-90)
