### ISSUE TITLE
Bug: Checkout on WooCommerce charges people in INR when the currency should be USD.

### ISSUE THREAD

**Issue by NerdvanaNC** [razorpay/razorpay-woocommerce#560]
On my store with international payments enabled, customers are charged in USD. But now, since Razorpay has updated their checkout flow, people checking out with USD10 worth of items in their cart are charged INR10 instead. How can this even happen?

**Comment by abdulwahidsharief** [comment]
@NerdvanaNC please let me know the change in wordpress admin for currency. have you changed it in wordpress admin -> woocommerce -> settings-> general -> Currency

**Comment by abdulwahidsharief** [comment]
@NerdvanaNC can we please have a quick google meet call to understand the issue

**Comment by abdulwahidsharief** [comment]
@NerdvanaNC please provide replicating steps for the issue

**Comment by NerdvanaNC** [comment]
@abdulwahidsharief Yes, we can get on a Google Meet call or I can send you screencasts via email. How can I reach you?

**Comment by abdulwahidsharief** [comment]
@NerdvanaNC please share the screencasts to abdul.sharief@razorpay.com include wordpress admin product pricing after currency change to USD and place one order in store(until rzp checkout modal opens). we can connect later if it is required.

**Comment by NerdvanaNC** [comment]
I have sent these details to you; did you receive my email?

**Comment by abdulwahidsharief** [comment]
@NerdvanaNC didn't received files can you please send here

**Comment by abdulwahidsharief** [comment]
@NerdvanaNC didn't received email. please send here

**Comment by NerdvanaNC** [comment]
![razorpayCheckoutINR2](https://github.com/razorpay/razorpay-woocommerce/assets/13850325/19bb8fe6-216f-4f43-8fb5-423e5e1534e0)
![razorpayCheckoutINR3](https://github.com/razorpay/razorpay-woocommerce/assets/13850325/0cb11737-d220-4cd8-86f2-dcc39c3de58c)
![razorpayCheckoutINR4](https://github.com/razorpay/razorpay-woocommerce/assets/13850325/680c0745-7dd7-438e-8542-352528b3c1f9)

**Comment by ramth05** [comment]
@NerdvanaNC , Please provide the steps to reproduce it.
Also help which version of plugin you are using in your site. Site url etc.  Please raise a support ticket with Razorpay as well.

**Comment by NerdvanaNC** [comment]
There are no special steps to recreate this issue, I have been using Razorpay checkout plugin version 4.6.7.

My store is correctly configured (as seen in the earlier images). But Razorpay still proceeds to process checkout with INR as the currency. It should be USD.

**Comment by NerdvanaNC** [comment]
**Fixed it myself.**

`Line 1130` of the file `woo-razorpay.php` in the function `getDefaultCheckoutArguments( $order )`.

Changed `'currency' => self::INR` to `'currency'  => 'USD'`.

I don't know why the default arguments for checkout from an order are hardcoded to `INR`, but in any case, your implementation of the function `getOrderCurrency( $order )` is faulty.

It's probably reverting back to the hardcoded value instead of returning an error. I don't really understand why you baked in a silent failure by hardcoding INR into the code.

I will keep trying to check and see if the implementation breaks, but it seemed to work just fine in my testing so far.

Thanks for nothing except for "please provide steps to reproduce bug" LMAO.
