### ISSUE TITLE
paytm pay with woocommerce

### ISSUE THREAD

**Issue by harianv** [razorpay/razorpay-woocommerce#57]
Notice: WC_Shortcode_Checkout->output was called with an argument that is deprecated since version 2.1! "order" is no longer used to pass an order ID. Use the order-pay or order-received endpoint instead. in /var/www/html/wp-includes/functions.php on line 4023

ORDER NUMBER:
6700
DATE:

Notice: order_date was called
incorrectly
. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/Total/page.php'), wpex_get_template_part, get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-layout.php'), get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-content.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/Total/vc_templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/plugins/js_composer/in in /var/www/html/wp-includes/functions.php on line 4139
September 8, 2017
TOTAL:
₹1,500.00
PAYMENT METHOD:
paytm
Thank you for your order, please click the button below to pay with paytm.

Notice: order_total was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/Total/page.php'), wpex_get_template_part, get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-layout.php'), get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-content.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/Total/vc_templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/plugins/js_composer/i in /var/www/html/wp-includes/functions.php on line 4139

Notice: billing_email was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/Total/page.php'), wpex_get_template_part, get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-layout.php'), get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-content.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/Total/vc_templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/plugins/js_composer in /var/www/html/wp-includes/functions.php on line 4139

Notice: billing_phone was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/Total/page.php'), wpex_get_template_part, get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-layout.php'), get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-content.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/Total/vc_templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/plugins/js_composer in /var/www/html/wp-includes/functions.php on line 4139

Notice: billing_first_name was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/Total/page.php'), wpex_get_template_part, get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-layout.php'), get_template_part, locate_template, load_template, require('/themes/Total/partials/page-single-content.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/Total/vc_templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/plugins/js_com in /var/www/html/wp-includes/functions.php on line 4139

Fatal error: Call to undefined function mcrypt_get_block_size() in /var/www/html/wp-content/plugins/paytm/encdec_paytm.php on line 6

**Comment by harianv** [comment]
how to fix issue?

**Comment by captn3m0** [comment]
The actual error here:

>Fatal error: Call to undefined function mcrypt_get_block_size() in /var/www/html/wp-content/plugins/paytm/encdec_paytm.php on line 6

is completely unrelated to the Razorpay WooCommerce plugin, and is likely because mcrypt is either not installed or not available in your PHP installation. See https://wiki.php.net/rfc/mcrypt-viking-funeral for more details.

**Comment by harianv** [comment]
can you please guide which encrypt method will support.

**Comment by harianv** [comment]
@captn3m0  Thank you for your reply can you tell which encrypt will work php 5.6.

**Comment by captn3m0** [comment]
@harianv Please contact Paytm Support regarding issues with the paytm plugin.
