### ISSUE TITLE
Changes in handling Callback url as per WC 2.0

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-woocommerce#59]
The callback URL that our plugin is using is of the following format:

http://yoursite.com/?wc-api=CALLBACK

Since Woocommerce 2.0+ they have introduced new format as

http://yoursite.com/wc-api/CALLBACK/ 

You can check for woocommerce plugin version and apply the appropriate format.

Reference : https://docs.woocommerce.com/document/wc_api-the-woocommerce-api-callback/

ref: 96129

**Comment by Mayur-Wadpalliwar** [comment]
ref: 98031

**Comment by captn3m0** [comment]
Related: https://github.com/razorpay/razorpay-woocommerce/issues/3

The old format is still supported.

**Comment by captn3m0** [comment]
This is now switched in #60
