### ISSUE TITLE
Parse error on mobile site

### ISSUE THREAD

**Issue by ajayrds** [razorpay/razorpay-woocommerce#6]
Hi,

Payment options show up ok, was able to enter credit card details as well. But after clicking on Pay Rs.X, a new window opened with blank url field which did not load a page. On going back to payment tab, in place os 'Pay Rs. X', 'Parse error' is showing up.
Tested on Ghostery browser on Redmi prime 2, OS - Android 5.1.1.
The same works on Chrome browser though.
![screenshot_2016-08-13-19-43-07_com ghostery android ghostery](https://cloud.githubusercontent.com/assets/6838673/17643671/9f7cea1c-618e-11e6-9d38-86b271034156.png)

**Comment by captn3m0** [comment]
Thanks a lot for the report. Taggging @razorpay/frontend to look into this.

**Comment by pronav** [comment]
Ghostery browser seems to be hijacking some of the network calls to our servers. This doesn't happen with ghostery extention in FF/Chrome, though. Trying to find why this is happening and get around it.

**Comment by captn3m0** [comment]
@pronav can we close this?

**Comment by pronav** [comment]
Has been fixed. Ghostery was blocking some ajax calls, added normal form submission in popup as a fallback.

**Comment by captn3m0** [comment]
Anyway we can stop Ghostery from blocking us?

**Comment by pronav** [comment]
It probably isn't a rule on ghostery's side (extensions work fine). Rather their browser is problematic. It's an outdated chrome webview (based on Chrome 33) and is somewhat buggy.
