### ISSUE TITLE
Plugin doesn't work properly with custom order creation

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-woocommerce#64]
If merchants are using custom order creation plugin other than normal woo-Commerce order creation, then plugin doesn't work correctly.

Ref: 98963

**Comment by tessie** [comment]
@Mayur-Wadpalliwar  Could you suggest me a plugin so that I can reproduce

**Comment by Mayur-Wadpalliwar** [comment]
Have no idea. but you can try here: https://www.powr.io/tutorials/how-to-add-order-form-plugin-to-your-wordpress-site

**Comment by Mayur-Wadpalliwar** [comment]
Also, the zendesk ticket no is: `98963`. You can refer this ticket and ask the customer

**Comment by tessie** [comment]
@Mayur-Wadpalliwar  Can you please assign in a sprint cc @sunnyagg

**Comment by captn3m0** [comment]
Stale issue, closing
