### ISSUE TITLE
Update settlement i.d back to order

### ISSUE THREAD

**Issue by ajayrds** [razorpay/razorpay-woocommerce#7]
This is not an issue really, could be classified as a Feature request or Suggestion.
Currently, I see that the Order notes is updated with Razorpay payment i.d for every successful payment. Is it possible to similarly add the settlement i.d to the order once settlement is processed? The link between payment i.d and settlement i.d clearly already exists.

**Comment by captn3m0** [comment]
Thanks for the suggestion. Since, the settlement could happen anytime, it would be an async step (since payment flow doesn't include settlement id, which is generated later).

Maybe something like a "fetch settlement details" option somewhere on the order/payments screen.

**Comment by ajayrds** [comment]
True. A button in woocommerce orders page to fetch all payment i.ds or in a button in each order page for fetching payment i.d for that order should be convenient.

**Comment by KoolPal** [comment]
@captn3m0 This would be great if it could be added!
