### ISSUE TITLE
Shorten successful payment message

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-woocommerce#71]
https://github.com/razorpay/razorpay-woocommerce/blob/f68c9c2571a8bab1aa9312f3a6a733b7248391db/razorpay-payments.php#L875

**Comment by captn3m0** [comment]
explain reduce please?

**Comment by Mayur-Wadpalliwar** [comment]
Merchant do not want this long message and wants us to reduce the sentence something to `Thank you for shopping with us. Your account has been charged and your transaction is successful.`

**Comment by captn3m0** [comment]
Closing for https://github.com/razorpay/razorpay-woocommerce/issues/76
