### ISSUE TITLE
404 error after checkout - here's the fix needed

### ISSUE THREAD

**Issue by anant-QwertyWorks** [razorpay/razorpay-woocommerce#90]
you need in line 341 of razorpay-payments.php replace '/wc-api/' with  '/?wc-api='

**Comment by jpeevi** [comment]
Hi,
Can you share the version of WooCommerce and Wordpress which you're using?

**Comment by anant-QwertyWorks** [comment]
Wordpress version Version 4.9.8
WooCommerce version 3.4.4

________________________________

**Comment by jpeevi** [comment]
Hi,
We're only able to recreate the issue if the permalink is set to plain. For all other pretty permalink formats (like Day and name, Month and name,Numeric etc)  '/wc-api/' works fine.

**Comment by anant-QwertyWorks** [comment]
Right, my permalink setting is /index.php/%postname%/

I had to make this change to get it to work.

**Comment by captn3m0** [comment]
Marking as resolved.

**Comment by ravijordan** [comment]
this is my permalink, but still it's nor working
i am getting response as 1
![image](https://user-images.githubusercontent.com/11586523/66681178-c4ef3400-ec8f-11e9-8db0-74e942d4da99.png)
Permalink 
![image](https://user-images.githubusercontent.com/11586523/66682535-06351300-ec93-11e9-9a6b-9cda5b7ca952.png)
