### ISSUE TITLE
Issues with WooCommerce Integration - ID do not exist

### ISSUE THREAD

**Issue by sidkvn** [razorpay/razorpay-woocommerce#92]
Hello,

We are using Razorpay in our WP site with Woo-commerce, it was working till last 2 months but currently seems some issue with Razorpay plugin update. It would be great if we get a technical assistance.

After payment it give as a issue as "ID do not exist". Snapshot of the same.
![ira1](https://user-images.githubusercontent.com/13463513/46193147-c9fa7300-c31a-11e8-96df-fb7ec396001e.jpg)
![Uploading ira2.jpg…]()

**Comment by jpeevi** [comment]
HI,

![screenshot 2018-09-28 at 12 47 53 pm](https://user-images.githubusercontent.com/5638276/46194177-45115880-c31e-11e8-87cd-ff3d0175a565.png)

The orders creation API call is failing on your server with cURL Error (7). 

This can be resolved by enforcing TLS v1.2 on all the outbound requests from your server.
