### ISSUE TITLE
Untested Plugin

### ISSUE THREAD

**Issue by artbyankitaraut** [razorpay/razorpay-woocommerce#94]
i activated the 'razorpay for woocommerce' plugin with my wordpress site, i get a message "Warning: This plugin has not been tested with your current version of WordPress."
would this cause issue with my transactions?

Razorpay for WooCommerce Version: 1.6.2
WooCommerce version: 3.5.2
WordPress version: 5.0.1

**Comment by captn3m0** [comment]
Thanks for the report. This is because we haven't pushed a release for the 5.0 wordpress release as of yet.

If you face any issues with WordPress 5.0, please let us know. /cc @vivekagarwal1984

**Comment by artbyankitaraut** [comment]
how long will it take to release the new version of this plugin?
would the plugin affect my transactions because it is untested?

**Comment by captn3m0** [comment]
5.2.1 is now supported in the latest release (2.0.1)
