### ISSUE TITLE
The cart doesn't reset after successful payment

### ISSUE THREAD

**Issue by thesfboy** [razorpay/razorpay-woocommerce#95]
I'm using WooCommerce 3.5.3 with Wordpress 5.0.2. During testing, I have observed that after a successful payment, the cart doesn't reset to zero. I've tried many settings including disabling lazy loading of all items but still the cart doesn't update to zero after a successful payment. Other payment gateways like PayPal or PayTM don't have this issue. The thing is, I like the interface provided by Razorpay and would definitely want to have it on my live site. It seems you guys have ignored development on the WooCommerce platform for more than a year which is a shame. Hope I can get a resolution to this within a day or so.

**Comment by captn3m0** [comment]
This is resolved on current latest master.
