### ISSUE TITLE
Stable Plugin 1.6.3 not on Wordpress Store

### ISSUE THREAD

**Issue by thesfboy** [razorpay/razorpay-woocommerce#96]
The documentation on Github shows a stable plugin of 1.6.3 whereas the one available on Wordpress.com is 1.6.2. When will the new plugin be available for normal users. 1.6.2 doesn't update the cart after successful payments which leads to a terrible user experience and also the payments don't reflect on Google/Facebook Analytics.

**Comment by imanuelrajan** [comment]
Is Razorpay is compatible?? Are you using it now??? I need to integrate it to my website. So thus I'm asking you an opinion.

**Comment by thesfboy** [comment]
It's useless to me. The cart doesn't become zero on a successful checkout.
It's a known issue acknowledged even by them. They haven't updated the
plug-in in a long time. Use PayPal and PayTM like I do. Also, razorpay
doesn't support PayTM.

**Comment by captn3m0** [comment]
1.6.3 has been published on wordpress.com
