### ISSUE TITLE
Not Yet Fixed: Shorten successful payment message

### ISSUE THREAD

**Issue by KoolPal** [razorpay/razorpay-woocommerce#97]
Refer: #71 & #76 Both tickets have been closed but the latest version from Wordpress.org still shows

![image](https://user-images.githubusercontent.com/454883/52535336-206cc900-2d73-11e9-8aa7-f753be102017.png)

**Comment by imanuelrajan** [comment]
@KoolPal Is Razorpay for WooCommerce plugin is compatible with latest version of WordPress and WooCommerce???

Do you have any problem???

I'm going to integrate it to my website.so thus I'm asking you a opinion.

**Comment by KoolPal** [comment]
@imanuelrajan I am **NOT** using it at present since I require this for International Transactions and this is not handled correctly by this version of the plugin.

In addition, the above error reported by  me is also not fixed by them.

**Comment by imanuelrajan** [comment]
Okay thank you

**Comment by captn3m0** [comment]
The fix is released in 1.6.5 today
