### ISSUE TITLE
Payment not updating/capturing on WooCommerce

### ISSUE THREAD

**Issue by sumt7** [razorpay/razorpay-woocommerce#98]
Hi there,

We've been using Razorpay(Rzp) successfully but since past one week most of our transactions are not being captured in one go and getting server timeout error and those which are captured is reflected as canceled on the WooC order dashboard but able see the successful transactions on Rzp Dashboard. 

When contacted the WP Support here's there reply.

> No, I mean to say there isn't an error logged that I can see. If the payment is processed by Razorpay and it is not updating the orders, the issue is related to the plugin.

I would tell them you have multiple orders where the payment is processed by Razorpay but the order in WooCommerce is not updated and there are not related errors in the error log.

> 
Here're the screenshots: https://prnt.sc/mkm2b9
http://prntscr.com/mkml6z
So please help.

![rpy error](https://user-images.githubusercontent.com/9494546/52724295-1a762280-2fd5-11e9-8d99-030199589c88.png)

**Comment by captn3m0** [comment]
Please create a support ticket for this via https://razorpay.com/support/#request/merchant/technical-assistance
