### ISSUE TITLE
RAZORPAY ERROR: Order creation failed with the message: 'The WooCommerce Currency Switcher plugin is missing.'.

### ISSUE THREAD

**Issue by KoolPal** [razorpay/razorpay-woocommerce#99]
Hi,

This seems to be linked to #41 WooCommerce multi-currency support

Now that you have launched the acceptance of International Credit Cards this plugin should accept payments in the 92 International currencies supported by you.

I should NOT need to use the WooCommerce Currency Switcher plugin anymore to convert the currency to INR!!

In a test order, I am seeing the below error:
![image](https://user-images.githubusercontent.com/454883/52766691-f9054d00-304d-11e9-80b4-74eab4816908.png)

Please fix.

**Comment by KoolPal** [comment]
Latest update today **STILL** shows the above reported issue! When are you going to support international currency INSTEAD of currency conversion??

Today's changelog

    1.6.3
    Allows for null values in displayAmount
    **Better support for international currency conversion**
    Support for custom order success message

**Comment by captn3m0** [comment]
The 1.6.3 update was tagged quite some time back, and not released on Wordpress plugin directory. It was just released today, but it doesn't have native multi-currency support.

We have released native multi-currency support today with `2.0.0-beta`, which will graduate to a stable 2.0 release soon. Please try it out at https://github.com/razorpay/razorpay-woocommerce/releases/tag/v2.0.0-beta and let us know if you face any issues.
